"""allow optional profile fields

Revision ID: 3cc2c8d336a2
Revises: c58c98115437
Create Date: 2026-09-15 22:19:24.811929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc2c8d336a2'
down_revision: Union[str, Sequence[str], None] = 'c58c98115437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coach_profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('student_profiles', 'education',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'education',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('coach_profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
