"""create initial tables

Revision ID: c58c98115437
Revises: 
Create Date: 2026-09-15 20:04:47.211088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58c98115437'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'COACH', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('coach_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('session_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.CheckConstraint('session_fee >= 0', name='check_session_fee_nonnegative'),
    sa.CheckConstraint('years_experience >= 0', name='check_years_experience_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_coach_profiles_id'), 'coach_profiles', ['id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.create_table('coach_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_skills_id'), 'coach_skills', ['id'], unique=False)
    op.create_index(op.f('ix_coach_skills_skill'), 'coach_skills', ['skill'], unique=False)
    op.create_table('coaching_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('student_message', sa.Text(), nullable=True),
    sa.Column('coach_remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='check_duration_positive'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profiles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_sessions_coach_id'), 'coaching_sessions', ['coach_id'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_id'), 'coaching_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_status'), 'coaching_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_student_id'), 'coaching_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaching_sessions_student_id'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_status'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_id'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_coach_id'), table_name='coaching_sessions')
    op.drop_table('coaching_sessions')
    op.drop_index(op.f('ix_coach_skills_skill'), table_name='coach_skills')
    op.drop_index(op.f('ix_coach_skills_id'), table_name='coach_skills')
    op.drop_table('coach_skills')
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_coach_profiles_id'), table_name='coach_profiles')
    op.drop_table('coach_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
